pro/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')), 
    path("adminapp/",include(('adminapp.urls','adminapp'),namespace="adminapp")),     
    path("studentapp/",include(('studentapp.urls','studentapp'),namespace="studentapp")),     
    path("teacherapp/",include(('teacherapp.urls','teacherapp'),namespace="teacherapp")),     
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

studentapp/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('studentapp/',views.studentdash,name="studentdash"),
    path('studentprofile/',views.studentprofile,name="studentprofile"),
    path('studentlogout/',views.studentlogout,name="studentlogout"),
    path('studentsubject/',views.studentsubject,name="studentsubject"),
    path('studentattend/',views.studentattend,name="studentattend"),
    path('studentdash/',views.studentdash,name="studentdash"),
]

urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')), 
    path("adminapp/",include(('adminapp.urls','adminapp'),namespace="adminapp")),     
    path("studentapp/",include(('studentapp.urls','studentapp'),namespace="studentapp")),     
    path("teacherapp/",include(('teacherapp.urls','teacherapp'),namespace="teacherapp")),     
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

studentapp/models.py
from django.db import models

# Create your models here.

studentapp/views.py
from django.shortcuts import render,redirect
from user . models import *
from django.core.files.storage import FileSystemStorage

# Create your views here.

def studentdash(request):
    try:
        if request.session['student']!=None:
            studentid=request.session['student']
            stu=Student.objects.get(email=studentid)
            sub_count=Subject.objects.all().count()
            return render(request,'studentdash.html',{'stu':stu,'sub_count':sub_count})
    except:
        return redirect('login')
    
def studentprofile(request):
    try:
        if request.session['student']!=None:
            studentid=request.session['student']
            stu=Student.objects.get(email=studentid)
            if request.method=="POST":
                pic=request.FILES['pic']
                fs= FileSystemStorage()
                filename=fs.save(pic.name, pic)
                stu.pic=filename
                stu.save()
                return redirect('studentapp:studentprofile')
            return render(request,'studentprofile.html',{'stu':stu})
    except:
        return redirect('login')
    
def studentlogout(request):
    try:
        if request.session['student']!=None:
            del request.session['student']
            return redirect('login')
    except:
        return redirect('login')
    
def studentsubject(request):
    try:
        if request.session['student']!=None:
            studentid=request.session['student']
            stu=Student.objects.get(email=studentid)
            sub=Subject.objects.filter(classid=stu.sclass)
            return render(request,'studentsubject.html',{'stu':stu,'sub':sub})
    except:
        return redirect('login')
    
def studentattend(request):
    try:
        if request.session['student']!=None:
            studentid=request.session['student']
            stu=Student.objects.get(email=studentid)
            att=StudentAttendance.objects.filter(studentid=stu.id)
            return render(request,'studentattend.html',{'stu':stu,'att':att})
    except:
        return redirect('login')

studentapp/templates/studentattend.html
{% extends "studentparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Student Attendance</h1>   
            <table class="table text-light mx-auto w-75 table-border" >
                <tr>
                    <th>S.no</th>
                    <th>Date</th>
                    <th>Attendance</th>
                 </tr>
                {% for a in att %}
                    <form method="post">
                        {% csrf_token %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{a.date}}</td>
                            <td>{{a.status}}</td>
                      </tr>
                    </form>
                {% endfor %}
            </table>
               
        </div>
    </div>
{% endblock body %}

studentapp/templates/studentdash.html
{% extends "studentparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Student Home</h1>
            <br>             
                </div>
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div class="card shadow p-2">
                       <div> <i class="fa-solid fa-user-graduate fs-2 text-success"></i><span class="ms-3 fs-5 fw-bold">Total_Subjects
                    </span>
                    
                    <h2 class="text-center pt-3 text-success">{{sub_count}}</h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-3"></div>
            </div>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        </div>
    </div>
{% endblock %}
 

studentapp/templates/studentparent.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CRM For MARC Lab</title>
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
            <span>Student</span>
          </div>
          <ul class="nav">
            <li class="nav-item profile">
              <div class="profile-desc">
                <div class="profile-pic">
                  <div class="count-indicator">
                    {% if stu.pic %}
                    <img class="img-xs rounded-circle " src="{{stu.pic.url}}" alt="">
                    {% endif %}
                    <span class="count bg-success"></span>
                  </div>
                  <div class="profile-name">
                    <h5 class="mb-0 font-weight-normal">{{stu.name}}</h5>                    
                  </div>
                </div>
                <a href="#" id="profile-dropdown" data-bs-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-settings text-primary"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Profile Management</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-onepassword  text-info"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'studentapp:studentlogout' %}" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-calendar-today text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
                    </div>
                  </a>
                </div>
              </div>
            </li>            
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'studentapp:studentdash' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
           <li class="nav-item menu-items">
              <a class="nav-link" href="{%url 'studentapp:studentsubject'%}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Subjects</span>
              </a>
            </li>    
                    
            <li class="nav-item menu-items">
              <a class="nav-link" href="{%url 'studentapp:studentattend'%}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Attendance </span>
              </a>
            </li>    
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'studentapp:studentprofile' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">View Profile</span>
              </a>
            </li>    
          </ul>
        </nav>
        
        <div class="container-fluid page-body-wrapper">
        
          <nav class="navbar p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
              <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
              <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
              </button>
              <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item dropdown">
                  <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                    <div class="navbar-profile">
                      {% if stu.pic %}
                      <img class="img-xs rounded-circle" src="{{stu.pic.url}}" alt="">
                      {% endif %}
                      <p class="mb-0 d-none d-sm-block navbar-profile-name">{{stu.name}}</p>
                      <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                    <h6 class="p-3 mb-0">Profile</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-settings text-success"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Settings</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'studentapp:studentlogout' %}" class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-logout text-danger"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Log out</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <p class="p-3 mb-0 text-center">Advanced settings</p>
                  </div>
                </li>
              </ul>
              <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
              </button>
            </div>
          </nav>
          
          <div class="main-panel">
            <div class="content-wrapper">
              {% block body %}              

              {% endblock body %}
            </div>
          
            <footer class="footer">
              <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © LPCPS 2024</span>              
              </div>
            </footer>
          
          </div>
          
        </div>
        
      </div>
      <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    
    <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
    
    <script src="{% static 'assets/js/dashboard.js'%}"></script>
</body>
</html>

studentapp/templates/studentprofile.html
{% extends "studentparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">{{stu.name}} Profile</h1>   
            <form method="post" class="row" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-sm-12 p-3">
                    <div class="mx-auto" style="max-width: 200px;">
                {%if stu.pic %}
                <img src="{{stu.pic.url}}" alt="" class="w-100" height="250">
                {% endif %}
                
                <input type="file" name="pic" class="form-control">
            </div>
            </div>
            <div class="col-sm-6 p-3">
                <label>NAME:</label>
                <input type="text" name="name" value="{{stu.name}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>FATHER'S NAME::</label>
                <input type="text" name="name" value="{{stu.fname}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>CLASS:</label>
                <input type="text" name="name" value="{{stu.sclass}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>EMAIL:</label>
                <input type="text" name="name" value="{{stu.email}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>NUMBER:</label>
                <input type="text" name="name" value="{{stu.mobile}}"readonly  class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>FATHER'S NUMBER:</label>
                <input type="text" name="name" value="{{stu.fnumber}}"readonly  class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>FEE PAID:</label>
                <input type="text" name="name" value="{{stu.sfee}}"readonly  class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>BALANCE:</label>
                <input type="text" name="name" value="{{stu.balance}}"readonly  class="form-control text-dark">
            </div>
            <div class="col-sm-12 text-center p-3">
                <button type="submit" class="btn btn-success">UPDATE</button>
            </div>
        
            </form>
             
        </div>
    </div>
{% endblock body %}

studentapp/templates/studentsubject.html
{% extends "studentparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Subjects</h1>   
            <table class="table text-light">
                <tr>
                    <th>S.No</th>
                    <th>Subject Name </th>
                    <th>Book Name</th>
                </tr>
                {% for s in sub %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{s.name}}</td>
                    <td>{{s.book}}</td>
                </tr>
                {% endfor %}
             </table>
        </div>
    </div>
{% endblock body %}