pro/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')), 
    path("adminapp/",include(('adminapp.urls','adminapp'),namespace="adminapp")),     
    path("studentapp/",include(('studentapp.urls','studentapp'),namespace="studentapp")),     
    path("teacherapp/",include(('teacherapp.urls','teacherapp'),namespace="teacherapp")),     
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

teacherapp/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('teacherapp/',views.teacherdash,name="teacherdash"),
    path('teacherlogout/',views.teacherlogout,name="teacherlogout"),
    path('teachersubject/',views.teachersubject,name="teachersubject"),
    path('teacherattend/',views.teacherattend,name="teacherattend"),
    path('teacherprofile/',views.teacherprofile,name="teacherprofile"),
    path('teacherdash/',views.teacherdash,name="teacherdash"),
]

urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')), 
    path("adminapp/",include(('adminapp.urls','adminapp'),namespace="adminapp")),     
    path("studentapp/",include(('studentapp.urls','studentapp'),namespace="studentapp")),     
    path("teacherapp/",include(('teacherapp.urls','teacherapp'),namespace="teacherapp")),     
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

teacherapp/models.py
from django.db import models

# Create your models here.

teacherapp/views.py
from django.shortcuts import render,redirect
from user.models import *
from django.core.files.storage import FileSystemStorage
import datetime

# Create your views here.

def teacherdash(request):
    try:
        if request.session['teacher']!=None:
            teacherid=request.session['teacher']
            teacher=Teacher.objects.get(email=teacherid)
            stu_count=Student.objects.all().count()
            sub_count=Subject.objects.all().count()
            return render(request,"teacherdash.html",locals())
        
    except:
        return redirect('login')
    
def teacherlogout(request):
    try:
        if request.session['teacher']!=None:
            del request.session['teacher']
            return redirect('login')
    except:
        return redirect('login')
    
def teachersubject(request):
    try:
        if request.session['teacher']!=None:
            teacherid=request.session['teacher']
            teacher=Teacher.objects.get(email=teacherid)
            sub=Subject.objects.filter(teacherid=teacher.id)
            return render(request,"teachersubject.html",locals())
    except:
        return redirect('login')
    
def teacherattend(request):
    # try:
        if request.session['teacher']!=None:
            teacherid=request.session['teacher']
            teacher=Teacher.objects.get(email=teacherid)
            students=Student.objects.filter(sclass=teacher.tclass)
            att=StudentAttendance.objects.filter(sclass=teacher.tclass)
            if request.method=="POST":
                studentid=request.POST['studentid']
                studentname=request.POST['studentname']
                sclass=request.POST['sclass']
                d=datetime.datetime.today()
                date=d.strftime("%Y-%m-%d")
                status=request.POST['status']
                stu=StudentAttendance(studentid=studentid,studentname=studentname,sclass=sclass,date=date,status=status)
                stu.save()
                return redirect('teacherapp:teacherattend')
            return render(request,"teacherattend.html",locals())
    # except:
        # return redirect('login')
    
def teacherprofile(request):
    try:
        if request.session['teacher']!=None:
            teacherid=request.session['teacher']
            teacher=Teacher.objects.get(email=teacherid)
            if request.method=="POST":
                pic=request.FILES['pic']
                fs= FileSystemStorage()
                filename=fs.save(pic.name, pic)
                teacher.pic=filename
                teacher.save()
                return redirect('teacherapp:teacherprofile')
            return render(request,"teacherprofile.html",locals())
    except:
        return redirect('login')

teacherapp/templates/teacherattend.html
{% extends "teacherparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Attendance</h1>
            <table class="table">
                <tr>
                    <th>Student Name</th>
                    <th>StudentId</th>
                    <th>Student Class</th>
                   <th>Status</th>
                    <th>Action</th>
                </tr>
                {% for s in students %}
                    <form method="post">
                        {% csrf_token %}
                        <tr>
                            <td>
                                <input type="text" name="studentname"value="{{s.name}}" class="form-control text-dark" readonly>
                            </td>
                            <td>
                                <input type="text" name="studentid" value="{{s.id}}" class="form-control text-dark" readonly>
                            </td>                            
                            <td>
                                <input type="text" name="sclass" value="{{teacher.tclass}}" class="form-control text-dark" readonly>
                            </td>
                           
                            <td>
                                <select name="status" class="form-select">
                                    <option value="P">P</option>
                                    <option value="A">A</option>
                                    </select>
                                    </td>
                                    <th>
                                        <button class="btn btn-success" type="submit">Done</button>
                                    </th>
                            </td>
                        </tr>
                    </form>
                {% endfor %}
            </table>
               
              
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-sm-12">
            <table class="table text-light mx-auto w-75 table-bordered" >
                <tr>
                    <th colspan="4" class="text-center">Student Attendance</th>
                </tr>
                <tr>
                    <th>S.no</th>
                    <th>Date</th>
                    <th>Student ID</th>
                    <th>Student Name</th>
                    <th>Attendance</th>
                
                </tr>
                {% for a in att %}
                    <form method="post">
                        {% csrf_token %}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{a.date}}</td>
                            <td>{{a.studentid}}</td>
                            <td>{{a.studentname}}</td>
                            <td>{{a.status}}</td>
                                   
                           
                        </tr>
                    </form>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock body %}

teacherapp/templates/teacherdash.html
{% extends "teacherparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Teacher Home</h1>            
        </div>
        <div class="col-sm-6 p-5">
            <div class="card shadow p-3">
               <div> <i class="fa-solid fa-user-graduate fs-2 text-warning"></i><span class="ms-3 fs-5 fw-bold">Students_Enrolled
            </span>
            <h2 class="text-center pt-3 text-warning">{{stu_count}}</h2>
                </div>
            </div>
        </div>
        <div class="col-sm-6 p-5">
            <div class="card shadow p-3">
                <div> <i class="fa-solid fa-book-open-reader fs-2 text-success"></i><span class="ms-3 fs-5 fw-bold">Total_Subjects
                </span>
                <h2 class="text-center pt-3 text-success">{{sub_count}}</h2>
                    </div>
            </div>
        </div>
        
    </div>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock body %}

teacherapp/templates/teacherparent.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SMS-Teacher</title>
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
</head>
<body>
    <div class="container-scroller">
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
            <span>Teacher</span>
          </div>
          <ul class="nav">
            <li class="nav-item profile">
              <div class="profile-desc">
                <div class="profile-pic">
                  <div class="count-indicator">
                    {% if teacher.pic %}
                    <img class="img-xs rounded-circle " src="{{teacher.pic.url}}" alt="">
                    {% endif %}
                    <span class="count bg-success"></span>
                  </div>
                  <div class="profile-name">
                    <h5 class="mb-0 font-weight-normal">{{teacher.name}}</h5>                    
                  </div>
                </div>
                <a href="#" id="profile-dropdown" data-bs-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-settings text-primary"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Profile Management</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="#" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-onepassword  text-info"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'teacherapp:teacherlogout' %}" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-calendar-today text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
                    </div>
                  </a>
                </div>
              </div>
            </li>            
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'teacherapp:teacherdash' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
           <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'teacherapp:teachersubject'%}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Subjects</span>
              </a>
            </li>    
                    
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'teacherapp:teacherattend' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Attendance </span>
              </a>
            </li>    
            <li class="nav-item menu-items">
              <a class="nav-link" href="{% url 'teacherapp:teacherprofile' %}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">View Profile</span>
              </a>
            </li>    
          </ul>
        </nav>
        
        <div class="container-fluid page-body-wrapper">
        
          <nav class="navbar p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
              <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
              <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
              </button>
              <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item dropdown">
                  <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                    <div class="navbar-profile">
                      {% if teacher.pic %}
                      <img class="img-xs rounded-circle" src="{{teacher.pic.url}}" alt="">
                      {% endif %}
                      <p class="mb-0 d-none d-sm-block navbar-profile-name">{{teacher.name}}</p>
                      <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                    <h6 class="p-3 mb-0">Profile</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-settings text-success"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Settings</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'teacherapp:teacherlogout' %}" class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-logout text-danger"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Log out</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <p class="p-3 mb-0 text-center">Advanced settings</p>
                  </div>
                </li>
              </ul>
              <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
              </button>
            </div>
          </nav>
          
          <div class="main-panel">
            <div class="content-wrapper">
              {% block body %}              

              {% endblock body %}
            </div>
          
            <footer class="footer">
              <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © LPCPS 2024</span>              
              </div>
            </footer>
          
          </div>
          
        </div>
        
      </div>
      <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    
    <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
    
    <script src="{% static 'assets/js/dashboard.js'%}"></script>
</body>
</html>

teacherapp/templates/teacherprofile.html
{% extends "teacherparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;"><u>{{teacher.name}} Profile</u></h1>   
            <form method="post" class="row" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-sm-12 p-3">
                    <div class="mx-auto" style="max-width: 200px;">
                {% if teacher.pic %}
                <img src="{{teacher.pic.url}}" alt="" class="w-100" height="200">
                {% endif %}
                
                <input type="file" name="pic" class="form-control">
            </div>
            </div>
            <div class="col-sm-6 p-3">
                <label>NAME:</label>
                <input type="text" name="name" value="{{teacher.name}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>Email::</label>
                <input type="text" name="name" value="{{teacher.email}}"readonly class="form-control text-dark">
            </div>
            
            <div class="col-sm-6 p-3">
                <label>Experience:</label>
                <input type="text" name="name" value="{{teacher.experience}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>Qualifications:</label>
                <input type="text" name="name" value="{{teacher.qualification}}"readonly class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>NUMBER:</label>
                <input type="text" name="name" value="{{teacher.number}}"readonly  class="form-control text-dark">
            </div>
            
            <div class="col-sm-6 p-3">
                <label>Class:</label>
                <input type="text" name="name" value="{{teacher.tclass}}"readonly  class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>Salary:</label>
                <input type="text" name="name" value="{{teacher.tsalary}}"readonly  class="form-control text-dark">
            </div>
            <div class="col-sm-6 p-3">
                <label>Join Date:</label>
                <input type="text" name="name" value="{{teacher.created}}"readonly  class="form-control text-dark">
            </div>
            
            <div class="col-sm-12 text-center p-4">
                <button type="submit" class="btn btn-success">UPDATE</button>
            </div>
        
            </form>
             
        </div>
    </div>
{% endblock body %}

teacherapp/templates/teachersubject.html
{% extends "teacherparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Subjects</h1>   
             <table class="table text-light">
                <tr>
                    <th>S.No</th>
                    <th>Subject Name </th>
                    <th>Book Name</th>
                </tr>
                {% for s in sub %}
                <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{s.name}}</td>
                    <td>{{s.book}}</td>
                </tr>
                {% endfor %}
             </table>
        </div>
    </div>
{% endblock body %}