adminapp/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views


urlpatterns =[
    path('dash',views.index,name="dash"),
    path('teacher',views.teacher,name="teacher"),
    path('student',views.student,name="student"),
    path('Attendance',views.attendance,name="Attendance"),
    path('classes',views.classes,name="classes"),
    path('subjects',views.subjects,name="subjects"),
    path('logout',views.logout,name="logout"),
    path('delteacher/<id>',views.delteacher,name="delteacher"),
    path('delstudent/<id>',views.delstudent,name="delstudent"),
    path('edit/<id>',views.edit,name="edit"),
    path('editteacher/<id>',views.editteacher,name="editteacher"),
    path('viewenquiry/',views.viewenquiry,name="viewenquiry"),
    path('admincp/',views.admincp,name="admincp"),
]

pro/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')), 
    path("adminapp/",include(('adminapp.urls','adminapp'),namespace="adminapp")),     
    path("studentapp/",include(('studentapp.urls','studentapp'),namespace="studentapp")),     
    path("teacherapp/",include(('teacherapp.urls','teacherapp'),namespace="teacherapp")),     
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urls.py
from django.contrib import admin
from django.urls import path,include
from user import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.userurls')), 
    path("adminapp/",include(('adminapp.urls','adminapp'),namespace="adminapp")),     
    path("studentapp/",include(('studentapp.urls','studentapp'),namespace="studentapp")),     
    path("teacherapp/",include(('teacherapp.urls','teacherapp'),namespace="teacherapp")),     
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/views.py
from django.shortcuts import render,redirect,reverse
import datetime
from user.models import *

# Create your views here.
def index(request):
    if request.session['username']!=None:
        stu_count=Student.objects.all().count()
        t_count=Teacher.objects.all().count()
        cl_count=Class.objects.all().count()
        sub_count=Class.objects.all().count()
        return render(request,'adminhome.html',locals())   
    else:
        return reverse(redirect('login'))   
    
def teacher(request):
    # try:
        if request.session['username']!=None:
            if request.method=="POST":
                name=request.POST['name']
                number=request.POST['number']
                email=request.POST['email']
                qua=request.POST['qualification']
                exp=request.POST['exp']
                tsalary=request.POST['tsalary']
                tclass=request.POST['tclass']
                address=request.POST['address']
                password=request.POST['password']
                created=datetime.datetime.today()
                teacher=Teacher (
                    name=name,
                    number=number,
                    email=email,
                    qualification=qua,
                    experience=exp,
                    tsalary=tsalary,
                    tclass=tclass, 
                    address=address,
                    created=created,
                    )
                teacher.save()
                log=LoginUser(username=email,password=password,usertype="teacher")
                log.save()
                t=Teacher.objects.all()
                cl=Class.objects.all()
                return render(request,'teacher.html',{'msg':"Teacher is Added",'t':t,'cl':cl})
            t=Teacher.objects.all()
            cl=Class.objects.all()
            return render(request,'teacher.html',{'t':t,'cl':cl})
    # except:
        # return redirect('login') 
    
def student(request):
    try:
        if request.session['username']!=None:
            if request.method=="POST":
                name=request.POST['name']
                fname=request.POST['fname']
                email=request.POST['email']
                mobile=request.POST['number']
                fnumber=request.POST['fnumber']
                dob=request.POST['dob']
                sclass=request.POST['sclass']
                sfee=request.POST['sfee']
                balance=request.POST['balance']
                address=request.POST['address']
                password=request.POST['password']
                stu=Student(
                    name=name,
                    fname=fname,
                    mobile=mobile,
                    email=email,
                    fnumber=fnumber,
                    dob=dob,
                    sclass=sclass,
                    sfee=sfee,
                    balance=balance,
                    address=address,
                )
                stu.save()
                log=LoginUser(username=email,password=password,usertype="student")
                log.save()
                msg="Student is added successfully"
                stu=Student.objects.all()
                cl=Class.objects.all()
                
                return render(request,'student.html',{'msg':msg,'stu':stu, 'cl':cl,})
            stu=Student.objects.all()
            cl=Class.objects.all()
            sub=Class.objects.all()
            return render(request,'student.html',{'stu':stu,'cl':cl})
    except:
        return redirect('login')


def attendance(request):
    try:
        if request.session['username']!=None:
            attend=StudentAttendance.objects.all()
            return render(request,'attendance.html',{'attend':attend})
    except:
        return render(request,'login')


    
def logout(request):
    try:
        if request.session['username']!=None:
            del request.session['username']
            return redirect('login')
    except:
        return redirect('login')
    
def delteacher(request,id):
    try:
        if request.session['username']!=None:
            Teacher.objects.get(id=id).delete()
            return redirect('adminapp:teacher')
    except:
        return redirect('login')
    
def delstudent(request,id):
    try:
        if request.session['username']!=None:
            Student.objects.get(id=id).delete()
            return redirect('adminapp:student')
    except:
        return redirect('login')
    
def edit(request,id):
    try:
        if request.session['username']!=None:
            stu=Student.objects.get(id=id)
            cl=Class.objects.all()
            if request.method=="POST":
                name=request.POST['name']
                fname=request.POST['fname']
                mobile=request.POST['number']
                email=request.POST['email']
                fnumber=request.POST['fnumber']
                dob=request.POST['dob']
                sclass=request.POST['sclass']
                sfee=request.POST['sfee']
                balance=request.POST['balance']
                address=request.POST['address']
                Student.objects.filter(id=id).update(
                    name=name,
                    fname=fname,
                    mobile=mobile,
                    email=email,
                    fnumber=fnumber,
                    dob=dob,
                    sclass=sclass,
                    sfee=sfee,
                    balance=balance,
                    address=address,
                    )
                return redirect('adminapp:student')
            return render(request,'edit.html',{'stu':stu,'cl':cl})
    except:
        return redirect('login')
        
def editteacher(request,id):
    try:
        if request.session['username']!=None:
            t=Teacher.objects.get(id=id)
            if request.method=="POST":
                name=request.POST['name']
                address=request.POST['address']
                email=request.POST['email']
                experience=request.POST['exp']
                number=request.POST['number']
                qualification=request.POST['qualification']
                tclass=request.POST['tclass']
                tsalary=request.POST['tsalary']
                # created=request.POST['created']
                
                Teacher.objects.filter(id=id).update(
                    name=name,
                    address=address,
                    email=email,
                    
                    experience=experience,
                    number=number,
                    qualification=qualification,
                    tclass=tclass,
                    tsalary=tsalary,
                    # created=created,
                    )
                return redirect('adminapp:teacher')
            return render(request,'editteacher.html',{'t':t})
    except:
        return redirect('login')
        
def classes(request):
    try:
        if request.session['username']!=None:
            c=Class.objects.all()
            if request.method=="POST":
                name=request.POST['name']
                roomno=request.POST['roomno']
                seats=request.POST['seats']
                c=Class(name=name,roomno=roomno,seats=seats)
                c.save()
                return redirect('adminapp:classes')
            return render(request,'classes.html',locals())
    except:
         return render(request,'login')
    
def subjects(request):
    try:
        if request.session['username']!=None:
            cl=Class.objects.all()
            sub=Subject.objects.all()
            teacher=Teacher.objects.all()
            if request.method=="POST":
                name=request.POST['name']
                classid=request.POST['classid']
                teacherid=request.POST['teacherid']
                book=request.POST['book']
                s=Subject(name=name,classid=classid,teacherid=teacherid,book=book)
                s.save()
                return redirect('adminapp:subjects')
            return render(request,'subjects.html',locals())
    except:
        return render(request,'login')
    
def viewenquiry(request):
    try:
        if request.session['username']!=None:
            enq=Enquiry.objects.all()
            return render(request,'viewenquiry.html',locals())   
    except:
        return redirect('login')

def admincp(request):
    # try:
        if request.session['username']!=None:
            adminid=request.session['username']
            if request.method=="POST":
                oldpassword=request.POST['oldpassword']
                newpassword=request.POST['newpassword']
                cpassword=request.POST['cpassword']
                try:
                    obj=LoginUser.objects.get(username=adminid,password=oldpassword)
                    if newpassword!=cpassword:
                        msg="Enter same Password"
                    elif oldpassword==obj.password:
                        LoginUser.objects.filter(username=adminid,password=oldpassword).update(password=newpassword)
                        return redirect('adminapp:logout')
                except:
                    return render(request,'admincp.html',{'msg':"Invali Old Password"})
            return render(request,'admincp.html',locals())   
    # except:
        # return redirect('login')
        

adminapp/templates/admincp.html
{% extends "adminparent.html" %}
{% block body %}
<div class="row">
    <div class="col-sm-10 mx-auto">
        <h2 class="text-center">Change Password</h2>
        <form method="post">
         {% csrf_token %}
            {% if msg %}
            <div class="alert alert-light" role="alert">{{msg}}</div>
            {% endif%}
            <table class="table text-light">
                <tr>
                    <td>Enter Old Password</td>
                    <td>
                        <input type="text" name="oldpassword" class="form-control">
                    </td>
                </tr>
           
                <tr>
                    <td>Enter New Password</td>
                    <td>
                        <input type="text" name="newpassword" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>Confirm Password</td>
                    <td>
                        <input type="text" name="cpassword" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td colspan="2" class="text-center">
                        <button type="submit" class="btn btn-success">Change</button>
                    </td>
                </tr>

            </table>
        </form>
    </div>
</div>
{% endblock%}

adminapp/templates/adminhome.html
{% extends "adminparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Dashboard</h1>   
        </div>
        <div class="row p-5">
        <div class="col-sm-4">
            <div class="card shadow p-3">
                <div class="text-center"><i class="fa-solid fa-user-graduate fs-3 text-success"></i>
                <span class="ms-3 fs-3"><b>Students Enrolled</b></span></div>
                <h1 class="text-center pt-3 text-success">{{stu_count}}</h1>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="card shadow p-3">
                <div class="text-center"><i class="fa-solid fa-chalkboard-user fs-3 text-primary"></i></i>
                    <span class="ms-3 fs-3"><b>Teachers </b></span></div>
                    <h1 class="text-center pt-3 text-primary">{{t_count}}</h1>
                </div>
            </div>
       
        <div class="col-sm-4">
            <div class="card shadow p-3">
                <div class="text-center"><i class="fa-solid fa-users-viewfinder fs-3 text-warning"></i></i></i>
                    <span class="ms-3 fs-3"><b>Classes </b></span></div>
                    <h1 class="text-center pt-3 text-warning">{{cl_count}}</h1>
                </div>
            </div>
        </div>
        </div>
        <div class="row p-3">
            <div class="col-sm-4"></div>
            <div class="col-sm-4">
                <div class="card shadow p-3">
                    <div class="text-center"><i class="fa-solid fa-users-viewfinder fs-3 text-secondary"></i></i></i>
                        <span class="ms-3 fs-3"><b>Subject </b></span></div>
                        <h1 class="text-center pt-3 text-secondary">{{sub_count}}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

adminapp/templates/adminparent.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School Management System</title>
    <link rel="stylesheet" href="{% static 'assets/vendors/mdi/css/materialdesignicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/css/vendor.bundle.base.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/vendors/jvectormap/jquery-jvectormap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/flag-icon-css/css/flag-icon.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/vendors/owl-carousel-2/owl.theme.default.min.css' %}">
    
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    
    <link rel="shortcut icon" href="{% static 'assets/images/favicon.png' %}" />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
      input{
        color:white !important;
      }
      ::placeholder{
        color:white !important;
      }
    </style>
</head>
<body>
    <div class="container-scroller">
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
          <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
            <span>SMS</span>
          </div>
          <ul class="nav">
            <li class="nav-item profile">
              <div class="profile-desc">
                <div class="profile-pic">
                  <div class="count-indicator">
                    <img class="img-xs rounded-circle " src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                    <span class="count bg-success"></span>
                  </div>
                  <div class="profile-name">
                    <h5 class="mb-0 font-weight-normal">{{cust.name}}</h5>                    
                  </div>
                </div>
                <a href="#" id="profile-dropdown" data-bs-toggle="dropdown"><i class="mdi mdi-dots-vertical"></i></a>
                <div class="dropdown-menu dropdown-menu-right sidebar-dropdown preview-list" aria-labelledby="profile-dropdown">
                 
                  <div class="dropdown-divider"></div>
                  <a href="{%url 'adminapp:admincp'%}" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-onepassword  text-info"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Change Password</p>
                    </div>
                  </a>
                  <div class="dropdown-divider"></div>
                  <a href="{%url 'adminapp:logout'%}" class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <div class="preview-icon bg-dark rounded-circle">
                        <i class="mdi mdi-calendar-today text-success"></i>
                      </div>
                    </div>
                    <div class="preview-item-content">
                      <p class="preview-subject ellipsis mb-1 text-small">Logout</p>
                    </div>
                  </a>
                </div>
              </div>
            </li>            
            <li class="nav-item menu-items">
              <a class="nav-link" href="{%url 'adminapp:dash'%}">
                <span class="menu-icon">
                  <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Dashboard</span>
              </a>
            </li>
           <li class="nav-item menu-items">
              <a class="nav-link" href="{%url 'adminapp:teacher'%}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Teacher </span>
              </a>
            </li>    
            <li class="nav-item menu-items">
              <a class="nav-link" href="{%url 'adminapp:student'%}">
                <span class="menu-icon">
                  <i class="mdi mdi-playlist-play"></i>
                </span>
                <span class="menu-title">Student</span>
              </a>
            </li>            
         
              <li class="nav-item menu-items">
                <a class="nav-link" href="{%url 'adminapp:classes'%}">
                  <span class="menu-icon">
                    <i class="mdi mdi-playlist-play"></i>
                  </span>
                  <span class="menu-title">Classes</span>
                </a>
              </li>    
              <li class="nav-item menu-items">
                <a class="nav-link" href="{%url 'adminapp:subjects'%}">
                  <span class="menu-icon">
                    <i class="mdi mdi-playlist-play"></i>
                  </span>
                  <span class="menu-title">Subjects</span>
                </a>
              </li>  
              <li class="nav-item menu-items">
                <a class="nav-link" href="{%url 'adminapp:viewenquiry'%}">
                  <span class="menu-icon">
                    <i class="mdi mdi-playlist-play"></i>
                  </span>
                  <span class="menu-title">View Enquiry</span>
                </a>
              </li>   
            </li>    
          </ul>
        </nav>
        
        <div class="container-fluid page-body-wrapper">
        
          <nav class="navbar p-0 fixed-top d-flex flex-row">
            <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
              <a class="navbar-brand brand-logo-mini" href="#"><img src="{% static 'assets/images/logo-mini.svg' %}" alt="logo" /></a>
            </div>
            <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
              <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
                <span class="mdi mdi-menu"></span>
              </button>
              <ul class="navbar-nav navbar-nav-right">
                <li class="nav-item dropdown">
                  <a class="nav-link" id="profileDropdown" href="#" data-bs-toggle="dropdown">
                    <div class="navbar-profile">
                      <img class="img-xs rounded-circle" src="{% static 'assets/images/faces/face15.jpg' %}" alt="">
                      <p class="mb-0 d-none d-sm-block navbar-profile-name">{{cust.name}}</p>
                      <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                    <h6 class="p-3 mb-0">Profile</h6>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-settings text-success"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Settings</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{%url 'adminapp:logout'%}" class="dropdown-item preview-item">
                      <div class="preview-thumbnail">
                        <div class="preview-icon bg-dark rounded-circle">
                          <i class="mdi mdi-logout text-danger"></i>
                        </div>
                      </div>
                      <div class="preview-item-content">
                        <p class="preview-subject mb-1">Log out</p>
                      </div>
                    </a>
                    <div class="dropdown-divider"></div>
                    <p class="p-3 mb-0 text-center">Advanced settings</p>
                  </div>
                </li>
              </ul>
              <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
                <span class="mdi mdi-format-line-spacing"></span>
              </button>
            </div>
          </nav>
          
          <div class="main-panel">
            <div class="content-wrapper">
              {% block body %}              

              {% endblock body %}
            </div>
          
            <footer class="footer">
              <div class="d-sm-flex justify-content-center justify-content-sm-between">
                <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © MARC Lab. 2024</span>              
              </div>
            </footer>
          
          </div>
          
        </div>
        
      </div>
      <script src="{% static 'assets/vendors/js/vendor.bundle.base.js' %}"></script>
    
    <script src="{% static 'assets/vendors/chart.js/Chart.min.js' %}"></script>
    <script src="{% static 'assets/vendors/progressbar.js/progressbar.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
    <script src="{% static 'assets/vendors/owl-carousel-2/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery.cookie.js' %}" type="text/javascript"></script>
    
    <script src="{% static 'assets/js/off-canvas.js' %}"></script>
    <script src="{% static 'assets/js/hoverable-collapse.js' %}"></script>
    <script src="{% static 'assets/js/misc.js' %}"></script>
    <script src="{% static 'assets/js/settings.js' %}"></script>
    <script src="{% static 'assets/js/todolist.js' %}"></script>
    
    <script src="{% static 'assets/js/dashboard.js'%}"></script>
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
    <script>
      AOS.init();
    </script>
</body>
</html>

adminapp/templates/attendance.html
{% extends "adminparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center;">Attendance </h1>   
              <table class="table">
                <tr>
                    <th>S.no</th>
                    <th>Date</th>
                    <th>Student Class</th>
                    <th>Student Name</th>
                </tr>
              </table>
        </div>
    </div>
{% endblock body %}

adminapp/templates/student.html
{% extends "adminparent.html" %}
{% block body %}
    <div class="row">
        <div class="col-sm-12">
            <h1 style="text-align:center">Student</h1>   
            <div class="row">
                <div class="col-sm-12">
                    <form method="post" class="p-3 text-light">
                        {%csrf_token%}
                        <h3>Add Student</h3>
                        {% if msg %}
                        <div class="alert alert-dark" role="alert">{{msg}}</div>
                        {% endif %}
                        <div class="row">
                            <div class="col-sm-6"><input type="text" name="name" class="form-control my-2" placeholder="Enter Name" required="True"></div>
                            <div class="col-sm-6"><input type="text" name="fname" class="form-control my-2" placeholder="Enter Father's Name" required="True"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-4"><input type="text" name="email" class="form-control my-2" placeholder="Enter Email"required="True"></div>
                            <div class="col-sm-4"><input type="number" name="number" class="form-control my-2" placeholder="Enter Mobile no."required="True"></div>
                            <div class="col-sm-4"><input type="text" name="password" class="form-control my-2" placeholder="Enter Password"required="True"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6"><input type="number" name="fnumber" class="form-control my-2" placeholder="Enter Father's Number"required="True"></div>
                            <div class="col-sm-6"><input type="date" name="dob" class="form-control my-2" placeholder="Enter DOB"required="True"></div>
                        </div>
                        <div class="row"><div class="col-sm-6">
                            <select name="sclass" class="form-select">
                                <option value="" selected>---Select Class---</option>
                                {% for c in cl%}
                                <option value="{{c.name}}">{{c.name}}</option>
                                {% endfor %}
                                </select>
                                </div>
                            
                            <div class="col-sm-6"><input type="text" name="sfee" class="form-control my-2" placeholder="Enter Fee"required="True"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6"><input type="text" name="balance" class="form-control my-2" placeholder="Enter Balance"required="True"></div>
                            <div class="col-sm-6">
                                <textarea name="address" class="form-control text-light" placeholder="Enter Address"required="True"></textarea>
                            </div>
                        </div>
                        <div class="row mt-2">
                            <div class="col-sm-12 text-center">
                                <button type="submit" class="btn btn-success d-inline-block my-auto my-2 px-4">Add</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div> 
            <div class="row my-3">
                <h2 class="text-center">Registered Student</h2>
                <div class="table-responsive">
                    <table class="table text-light">
                        <tr>
                            <td>S.no</td>
                            <td>Name</td>
                            <td>Fname</td>
                            <td>Email</td>
                            <td>Number</td>
                            <td>Fnumber</td>
                            <td>DOB</td>
                            <td>Class</td>
                            <td>Fee</td>
                            <td>Rest Fee</td>
                            <td>Address</td>
                            <td colspan="2">Action</td>
                        </tr>
                        {% for s in stu %}
                        <tr>
                            <td>{{s.id}}</td>
                            <td>{{s.name}}</td>
                            <td>{{s.fname}}</td>
                            <td>{{s.email}}</td>
                            <td>{{s.mobile}}</td>
                            <td>{{s.fnumber}}</td>
                            <td>{{s.dob}}</td>
                            <td>{{s.sclass}}</td>
                            <td>{{s.sfee}}</td>
                            <td>{{s.balance}}</td>
                            <td>{{s.address}}</td>
                            <td>
                                <a href="{%url 'adminapp:edit' id=s.id%}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <a href="{% url 'adminapp:delstudent' id=s.id%}" class="btn btn-danger">Delete</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                
            </div>
        </div>
    </div>
{% endblock body %}